## tensorflow的简单使用

In [5]:
import tensorflow as tf
import numpy as np

In [6]:
t = tf.add(1,2)

In [12]:
# 产生一个 1x2 矩阵
a = tf.constant([1.0,2.0])
b = tf.constant([3.0,4.0])
c = a * b
c

<tf.Tensor 'mul_1:0' shape=(2,) dtype=float32>

In [8]:
sess = tf.Session()
res = sess.run(c)
res

array([3., 8.], dtype=float32)

In [9]:
sess.close()

In [10]:
rr = tf.reshape(res, (2,1))

In [11]:
res2 = tf

### 流图1

In [19]:
x = tf.Variable([1,2])
a = tf.constant([3,3])
sub = tf.subtract(x,a) # x - a
add = tf.add(x,sub) # x + (x - a)

In [24]:
init = tf.global_variables_initializer() # 初始化变量
sess = tf.Session() # 定义会话
sess.run(init)
sess.run(add)

array([-1,  1])

### 流图2

In [26]:
x = tf.Variable(0)
add = tf.add(x,1)
update = tf.assign(x,add) # 赋值
init = tf.global_variables_initializer() # 初始化变量
sess = tf.Session() # 定义会话
sess.run(init)
sess.run(update)
sess.run(update)
sess.run(update)

3

### 填充

In [39]:
x1 = tf.placeholder(tf.int32, shape=(2,3), name='x1') # 填充
x1

<tf.Tensor 'x1_3:0' shape=(2, 3) dtype=int32>

In [40]:
w1 = tf.placeholder(tf.int32, shape=(3,2), name='w1')

In [41]:
z1 = tf.matmul(x1, w1) # 矩阵相乘

In [42]:
# 初始化
init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)

In [43]:
sess.run(z1, feed_dict={ x1: [ [1,2,3],[3,2,1] ], w1: [ [1,2],[3,4],[5,6] ] })

array([[22, 28],
       [14, 20]])